export default {
	Black: require('../../assets/fonts/Urbanist-Black.ttf'),
	BlackItalic: require('../../assets/fonts/Urbanist-BlackItalic.ttf'),
	Bold: require('../../assets/fonts/Urbanist-Bold.ttf'),
	BoldItalic: require('../../assets/fonts/Urbanist-BoldItalic.ttf'),
	ExtraBold: require('../../assets/fonts/Urbanist-ExtraBold.ttf'),
	ExtraBoldItalic: require('../../assets/fonts/Urbanist-ExtraBoldItalic.ttf'),
	ExtraLight: require('../../assets/fonts/Urbanist-ExtraLight.ttf'),
	ExtraLightItalic: require('../../assets/fonts/Urbanist-ExtraLightItalic.ttf'),
	Italic: require('../../assets/fonts/Urbanist-Italic.ttf'),
	Light: require('../../assets/fonts/Urbanist-Light.ttf'),
	LightItalic: require('../../assets/fonts/Urbanist-LightItalic.ttf'),
	Medium: require('../../assets/fonts/Urbanist-Medium.ttf'),
	MediumItalic: require('../../assets/fonts/Urbanist-MediumItalic.ttf'),
	Regular: require('../../assets/fonts/Urbanist-Regular.ttf'),
	SemiBold: require('../../assets/fonts/Urbanist-SemiBold.ttf'),
	SemiBoldItalic: require('../../assets/fonts/Urbanist-SemiBoldItalic.ttf'),
	Thin: require('../../assets/fonts/Urbanist-Thin.ttf'),
	ThinItalic: require('../../assets/fonts/Urbanist-ThinItalic.ttf'),
};
